title: Globetrotter Documentation
description: Documentation for Globetrotter's systems and services
theme: just-the-docs

footer_content: "Copyright &copy; Globetrotter. All rights reserved."

url: https://globetrottertravel.github.io

enable_copy_code_button: true

nav_enabled: true

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true


back_to_top: true
back_to_top_text: "Back to top"

callouts:
  warning:
    title: Warning
    color: red