title: Globetrotter Documentation
description: Documentation for Globetrotter's systems and services
theme: just-the-docs

footer_content: "Copyright &copy; Globetrotter. All rights reserved."

enable_next_prev: true

url: https://globetrottertravel.github.io

aux_links:
  Globetrotter Insight: https://insight.globetrotter.com.au/
